DROP TABLE SAMPLE_T;

CREATE TABLE SAMPLE_T (
    SAMPLE_NO      NUMBER               NOT NULL,
    SAMPLE_CONTENT VARCHAR2(100 BYTE),
    SAMPLE_EDITOR  VARCHAR2(100 BYTE),
    SAMPLE_DT      DATE,
    CONSTRAINT PK_SAMPLE PRIMARY KEY(SAMPLE_NO)
);

DROP SEQUENCE SAMPLE_SEQ;

CREATE SEQUENCE SAMPLE_SEQ NOCACHE;



//INSERT의 반환(RETURN)값은 1이면 성공, 0이면 실패
//JDBC : AUTO COMMIT  알아서 함 (내가 안 함), 자바 코드로 나오지 않음.
SELECT SAMPLE_NO, SAMPLE_CONTENT, SAMPLE_EDITOR, TO_CHAR(SAMPLE_DT, 'YYYY-MM-DD HH24:MI:SS') FROM SAMPLE_T;